services:
  - type: web
    name: DRSHEMA
    runtime: python
    buildCommand: pip install flask requests gunicorn && apt-get update -y && apt-get install -y espeak espeak-ng ffmpeg
    startCommand: gunicorn app:app --timeout 600 --workers 1
    plan: standard
