services:
  - type: web
    name: DRSHEMA
    runtime: python
    buildCommand: pip install flask requests gunicorn gtts && apt-get update -y && apt-get install -y ffmpeg espeak espeak-ng flite || pip install flask requests gunicorn gtts
    startCommand: gunicorn app:app --timeout 600 --workers 1
    plan: standard
