services:
  - type: web
    name: drshema-video-service
    runtime: python
    buildCommand: "apt-get update && apt-get install -y ffmpeg flite && pip install -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 600 --workers 2"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
